server:
  port: 19872
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  fetchRegistry: true

spring:
  application:
    name: product-service
  flyway:
    locations: classpath:/db/migration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_service?serverTimezone=Europe/Moscow&amp&useSSL=false
    username: root
    password: gtr120519
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
